name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox
        run: pip install tox

      - name: Run type checking
        run: tox -e precommit

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python tools
        run: |
          python -m pip install -U pip tox ltd-conveyor

      - name: Run Sphinx build
        run: tox -e sphinx

      - name: Upload to lsst.io
        if: ${{ github.event_name == 'push' && github.repository_owner == 'lsst-dm' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --gh --dir _build/html --product panda
